Fixed Nuxt Documentation build + added installation steps
nestriness/nestri pull request #120
Opened 2024-09-29 13:33 UTC by victorpahuus

2024-10-01 21:46 UTC, djpremier commented on apps/docs/content/2.nestri-node/3.getting-started.md
> +echo "https://netris.me/play/$SESSION_ID"
```suggestion
echo "https://nestri.io/play/$SESSION_ID"
```

2024-10-01 22:28 UTC, djpremier requested changes

2024-10-01 22:28 UTC, djpremier commented on apps/docs/content/2.nestri-node/3.getting-started.md
> +docker run --gpus all --device=/dev/dri --name netris -it --entrypoint /bin/bash -e SESSION_ID=<copy here> -v "$(pwd)":/game -p 8080:8080/udp --cap-add=SYS_NICE --cap-add=SYS_ADMIN ghcr.io/netrisdotm
```suggestion
docker run --gpus all --device=/dev/dri --name nestri -it --entrypoint /bin/bash -e SESSION_ID=<paste here> -v "$(pwd)":/game -p 8080:8080/udp --cap-add=SYS_NICE --cap-add=SYS_ADMIN ghcr.io/nestriness/nestri/server:nightly
```

2024-10-01 22:28 UTC, djpremier commented on apps/docs/content/2.nestri-node/3.getting-started.md
> +head /dev/urandom | LC_ALL=C tr -dc 'a-zA-Z0-9' | head -c 16
```suggestion
echo "$(head /dev/urandom | LC_ALL=C tr -dc 'a-zA-Z0-9' | head -c 16)"
```

2024-10-01 22:28 UTC, djpremier commented on apps/docs/content/2.nestri-node/3.getting-started.md
> +With your SESSION_ID ready, insert it into the command below, replacing `<copy here>` with your actual session ID. Then, run the command to start the Netris server:
```suggestion
With your SESSION_ID ready, insert it into the command below, replacing `<paste here>` with your actual session ID. Then, run the command to start the Nestri server:
```

2024-10-01 22:28 UTC, djpremier commented on apps/docs/content/2.nestri-node/3.getting-started.md
> +After executing the previous command, you'll be in a new shell within the container (example: `netris@3f199ee68c01:~$`). Perform the following checks:
```suggestion
After executing the previous command, you'll be in a new shell within the container (example: `nestri@3f199ee68c01:~$`). Perform the following checks:
```

2024-10-01 22:28 UTC, djpremier commented on apps/docs/content/2.nestri-node/3.getting-started.md
> +- With Wine: `netris-proton -wr <game>.exe`
```suggestion
- With Proton-GE: `nestri-proton -pr <game>.exe`
- With Wine: `nestri-proton -wr <game>.exe`
```

2024-10-01 22:28 UTC, djpremier commented on apps/docs/content/2.nestri-node/3.getting-started.md
> +### Step 3: Launch the Netris Server
```suggestion
### Step 3: Launch the Nestri Server
```

2024-10-01 22:28 UTC, djpremier commented on apps/docs/content/2.nestri-node/3.getting-started.md
> +2. Then, start the Netris server by running `/etc/startup.sh > /dev/null &`.
```suggestion
2. Then, start the Nestri server by running `/etc/startup.sh > /dev/null &`.
```

2024-10-02 12:20 UTC, wanjohiryan commented
LGTM >>

I will have to add Cloudflare support before merging

2024-10-03 10:14 UTC, victorpahuus commented
To deploy with Cloudflare Pages, you need to select **Nuxt.js** in the **Framework preset** field.
Then add `apps/docs` to the **Path** field, and then click deploy.
![deploy-cloudflare](https://github.com/user-attachments/assets/8893cbdf-f6a8-4e52-9d21-347240ea49b3)

2024-10-04 18:41 UTC, wanjohiryan approved these changes
LGTM >>

2024-10-04 18:42 UTC, merged